package BO;
// Generated 3-dec-2014 14:44:59 by Hibernate Tools 4.3.1



/**
 * TblCursist generated by hbm2java
 */
public class Cursist  implements java.io.Serializable {


     private Integer id;
     private int naam;
     private int adres;
     private int email;

    public Cursist() {
    }

    public Cursist(int naam, int adres, int email) {
       this.naam = naam;
       this.adres = adres;
       this.email = email;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getNaam() {
        return this.naam;
    }
    
    public void setNaam(int naam) {
        this.naam = naam;
    }
    public int getAdres() {
        return this.adres;
    }
    
    public void setAdres(int adres) {
        this.adres = adres;
    }
    public int getEmail() {
        return this.email;
    }
    
    public void setEmail(int email) {
        this.email = email;
    }




}


