package BO;
// Generated 3-dec-2014 14:44:59 by Hibernate Tools 4.3.1



/**
 * TblInschrijving generated by hbm2java
 */
public class Inschrijving  implements java.io.Serializable {


     private Integer id;
     private int moduleId;
     private int cursistId;

    public Inschrijving() {
    }

    public Inschrijving(int moduleId, int cursistId) {
       this.moduleId = moduleId;
       this.cursistId = cursistId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getModuleId() {
        return this.moduleId;
    }
    
    public void setModuleId(int moduleId) {
        this.moduleId = moduleId;
    }
    public int getCursistId() {
        return this.cursistId;
    }
    
    public void setCursistId(int cursistId) {
        this.cursistId = cursistId;
    }




}


