package BO;
// Generated 3-dec-2014 14:44:59 by Hibernate Tools 4.3.1



/**
 * TblLokaal generated by hbm2java
 */
public class Lokaal  implements java.io.Serializable {


     private Integer id;
     private String adres;
     private String nummer;
     private int aantalPlaatsen;

    public Lokaal() {
    }

    public Lokaal(String adres, String nummer, int aantalPlaatsen) {
       this.adres = adres;
       this.nummer = nummer;
       this.aantalPlaatsen = aantalPlaatsen;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getAdres() {
        return this.adres;
    }
    
    public void setAdres(String adres) {
        this.adres = adres;
    }
    public String getNummer() {
        return this.nummer;
    }
    
    public void setNummer(String nummer) {
        this.nummer = nummer;
    }
    public int getAantalPlaatsen() {
        return this.aantalPlaatsen;
    }
    
    public void setAantalPlaatsen(int aantalPlaatsen) {
        this.aantalPlaatsen = aantalPlaatsen;
    }




}


