package BO;
// Generated 3-dec-2014 14:44:59 by Hibernate Tools 4.3.1



/**
 * TblModule generated by hbm2java
 */
public class Module  implements java.io.Serializable {


     private Integer id;
     private String nummer;
     private int docentId;
     private int lokaalId;

    public Module() {
    }

    public Module(String nummer, int docentId, int lokaalId) {
       this.nummer = nummer;
       this.docentId = docentId;
       this.lokaalId = lokaalId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNummer() {
        return this.nummer;
    }
    
    public void setNummer(String nummer) {
        this.nummer = nummer;
    }
    public int getDocentId() {
        return this.docentId;
    }
    
    public void setDocentId(int docentId) {
        this.docentId = docentId;
    }
    public int getLokaalId() {
        return this.lokaalId;
    }
    
    public void setLokaalId(int lokaalId) {
        this.lokaalId = lokaalId;
    }




}


